# Site settings
title: Reason About
email: info@reasonabout.co
description: A blog that brings fresh insights and information from 30 web devs together in one space.
url: "http://reasonabout.co"
twitter_username: reasonabout_co
github_username:  reasonabout

# Build settings
markdown: kramdown
