# Site settings
title: Reason About
email: reasonabout@gmail.com
description: This is a blog that brings fresh insights and information from about 30 web dev students and instrucors together in one space.
url: "http://reasonabout.co"
twitter_username: reasonabout_co
github_username:  reasonabout

# Build settings
markdown: kramdown
